### ISSUE TITLE
[Feature] Option to disable mod in Accessibility settings

### ISSUE THREAD

**Issue by chorbintime** [Snownee/TextAnimator#1]
### Mod loader

Fabric

### Minecraft version

N/A

### Mod version

N/A

### Modloader version

N/A

### Modpack info

N/A

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Most of the mod's effects could make it difficult for those with dyslexia, or who otherwise have impaired reading skills, to read animated text.

There could be a button under "Accessibility Settings" that opens a menu for disabling different features of the mod. 
For example, the rainbow text would be fairly easy for a majority of people to read, but could still be difficult for some. Letting players disable individual effects would solve any readability issues that people may have.

**Comment by Snownee** [comment]
Is there a Forge edition of this mod currently?

**Comment by chorbintime** [comment]
> Is there a Forge edition of this mod currently?

No, I just left the modloader response as the default, which was Forge, due to it not being applicable. I apologize for any confusion. 

I have edited my original post to better represent what I mean.
