### ISSUE TITLE
Effects don't apply to combined/processed text.

### ISSUE THREAD

**Issue by ZeroLevels** [Snownee/TextAnimator#13]
### Mod loader

Forge

### Minecraft version

1.20.1

### Mod version

2.0.1

### Modloader version

47.1.47

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

(There are no errors in the log, it just doesn't function as expected)

### Issue description

Admittedly, I don't know if this is a limitation or something that can be fixed. Affects applied to certain things _work_, but they _mess up_ too.

Combined things, like sliding options (e.g. FOV), seem to show the closing tag on the animation _while still functioning_. This happens on things such as "Attack Speed" in weapon tooltips and the like as well.
![derpt](https://github.com/Snownee/TextAnimator/assets/3106890/b57966ca-91cd-4516-a615-cf5596544649)

I was trying to make a cutesy, cartoony kinda feel, and liked the shaky font for it. So I made a quick edit to the entirety of the default **en_us** language file. If you wanna use it to see what is/isn't working, here's that as well in resourcepack form.
[shaky_font_RP.zip](https://github.com/Snownee/TextAnimator/files/12643062/shaky_font_RP.zip)

**Comment by Snownee** [comment]
unfortunately, this is the vanilla's behavior. the same applies to '§', for example:

```
/tellraw @a {"translate":"","fallback":"\u00a71test%stest","with":[{"text":"123"}]}
```

result:

![image](https://github.com/Snownee/TextAnimator/assets/16059084/356e8017-ca36-43bb-8a9b-84da8e803b32)

batch replacement does not work here.
