### ISSUE TITLE
Animated Glowing Text

### ISSUE THREAD

**Issue by Snugs** [Snownee/TextAnimator#14]
### Mod loader

Forge

### Minecraft version

1.20.1

### Mod version

2.0.1

### Modloader version

Forge 47.1.84

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Not sure if this would be considered a bug or an enhancement, but I noticed when applying glow ink to a sign that the glowing border around the text does not animate with the text... is it possible to amend this? I understand how much of a pain it could potentially be to add in, so totally understand if you decide not to... just curious :D

**Comment by SettingDust** [comment]
It's a bug that TA effects will lose when modifying the style. TextColor for here
