### ISSUE TITLE
Doesn't work with Emojiful

### ISSUE THREAD

**Issue by papamaionise** [Snownee/TextAnimator#16]
### Mod loader

Fabric

### Minecraft version

1.20.1

### Mod version

2.01

### Modloader version

fabric mod loadder 0.15.3

### If bug:

- [x] Can you reproduce this issue with relevant mods only?

### Issue description

Text doesn't animates with emojiful mod
but with out it text animates

**Comment by Snownee** [comment]
Hello, I can't reproduce this issue

**Comment by papamaionise** [comment]
> Hello, I can't reproduce this issue

Issue occurs when 
Text Animator is used with Emojiful mod 
https://modrinth.com/mod/emojiful/versions
so a compatibility issue sorry for responding late

**Comment by Snownee** [comment]
Can you make a video of that?

**Comment by papamaionise** [comment]
https://github.com/Snownee/TextAnimator/assets/126779287/059ab6ae-9754-456d-b6a1-0a314491e8c2

**Comment by Snownee** [comment]
https://youtu.be/K8XTeplTOjQ

**Comment by papamaionise** [comment]
> https://youtu.be/K8XTeplTOjQ

It's a private video

**Comment by Snownee** [comment]
> > https://youtu.be/K8XTeplTOjQ
> 
> It's a private video

fixed now

**Comment by papamaionise** [comment]
> https://youtu.be/K8XTeplTOjQ

Ok so I have like 200 mods so maybe its because of two or more mods not just one
but removing emojiful mod resolves the issue
I search again

**Comment by papamaionise** [comment]
![Screenshot (1324)](https://github.com/Snownee/TextAnimator/assets/126779287/040c9029-50ba-4543-9832-2bf49313a882)
issue is happening with only these

**Comment by papamaionise** [comment]
![Screenshot (1325)](https://github.com/Snownee/TextAnimator/assets/126779287/dfa901c3-e704-4319-9a40-e7f12a81dccd)

ok now I have no idea
here are the mod versions I'm using
