### ISSUE TITLE
Crash!!!!!!!

### ISSUE THREAD

**Issue by baka943** [Snownee/TextAnimator#18]
### Mod loader

Forge

### Minecraft version

1.20.1

### Mod version

2.1.0

### Modloader version

Forge 47.2.19

### Modpack info

None

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://paste.ubuntu.com/p/cqYbXtvZQ3/

### Issue description

Can't startup the game, O_0?

**Comment by Snownee** [comment]
@SettingDust
