### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by vommythegreat** [Snownee/TextAnimator#2]
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

1.1.0

### Modloader version

43.2.6

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://gist.github.com/cuboxy/9edcb3dbdaad4db2c6cfc5da25dc8539

### Issue description

game loads completely and then crashes when trying to load title screen

**Comment by cuboxy** [comment]
now i can open the game but when i try to open a world it says "server sent an invalid packet" and then the world disappears
[latest.log](https://github.com/Snownee/TextAnimator/files/12152612/latest.log)
