### ISSUE TITLE
Caxton will render this mod ineffective.

### ISSUE THREAD

**Issue by MRCUOGUO** [Snownee/TextAnimator#23]
### Mod loader

Fabric

### Minecraft version

1.20.1

### Mod version

2.1.1

### Modloader version

fabric-loader-0.15.6.jar

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Using resource packs supported by the Caxton Mod will result in the Text Animator becoming ineffective.

**Comment by Snownee** [comment]
Added to the incompatible mod list now
