### ISSUE TITLE
kicked when loading world "server sent invalid packet"

### ISSUE THREAD

**Issue by vommythegreat** [Snownee/TextAnimator#3]
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

1.1.1

### Modloader version

43.2.6

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://gist.github.com/cuboxy/5c19882d555072e0596aef62f7e77756

### Issue description

game loads up just fine, but when i try to open a world it says "server sent an invalid packet" and then the world disappears

**Comment by Snownee** [comment]
It's unlikely to be caused by text animator

**Comment by vommythegreat** [comment]
it stopped happening when i disabled the mod
