### ISSUE TITLE
Unable to apply Text Animator effects when using Modern UI

### ISSUE THREAD

**Issue by CelestialAbyss** [Snownee/TextAnimator#8]
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

1.1.2

### Modloader version

43.2.21

### Modpack info

N/A

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

N/A

### Issue description

I am guessing this is a potential incompatibility or just not accounted for

With Modern UI installed:
![image](https://github.com/Snownee/TextAnimator/assets/30322176/d030935b-f421-40fa-bd16-80252976fa50)

With Modern UI disabled:
![image](https://github.com/Snownee/TextAnimator/assets/30322176/8a64e43a-a1c7-4f7b-adee-930286421453)

**Comment by Snownee** [comment]
Thanks for the suggestion. We have no plans for this at this time.

**Comment by CelestialAbyss** [comment]
Is it possible to list it as incompatible though, just to let users at least know?

**Comment by Snownee** [comment]
done that 👍
